# -- Hauptmenü --

[[main]]
  name = "Start"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Beiträge"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Karte"
  pageRef = "map"
  weight = 30

[[main]]
  identifier = "search"
  weight = 90
  [main.params]
    action = "search"
